name: careful_icarus
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: 1.8.0
  google_fonts: any
  sensors_plus: ^3.0.0
  flame_audio: ^1.3.0
  shared_preferences: "^2.1.2"
  restart_app: ^1.2.1
  dcdg: ^4.1.0
  vibration: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sprites/
    - assets/audio/sfx_wing.mp3
    - assets/audio/FlyingPenguins_Theme.mp3
